# general setup
tap "homebrew/bundle"
tap "romkatv/powerlevel10k"

# window management
cask "spectacle"

# shell tools
cask "iterm2"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"
brew "romkatv/powerlevel10k/powerlevel10k"

# core apps
cask "alfred"
cask "coconutbattery"
cask "google-chrome"
cask "ticktick"
cask "spotify"
cask "surfshark"
